
project_id = "kgyjjfaaldmmcbtvqbgo"

[functions.create-checkout-session]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.webhook]
verify_jwt = false
