// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgyjjfaaldmmcbtvqbgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtneWpqZmFhbGRtbWNidHZxYmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTI0ODAsImV4cCI6MjA2MTg4ODQ4MH0.ku8mO2gflazHHi6AlSuQb3jP1WdjCNx-Ffq-vSGdoBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);